<?php

Merakcamacol\Init::get_instance();
Merakcamacol\Relationships::get_instance();
Merakcamacol\Blocks\Accordion::get_instance();
Merakcamacol\Blocks\Accordions::get_instance();
Merakcamacol\Blocks\Animation::get_instance();
Merakcamacol\Blocks\Catalog::get_instance();
Merakcamacol\Blocks\FunderData::get_instance();
Merakcamacol\Blocks\FunderRelatedNews::get_instance();
Merakcamacol\Blocks\LatestPosts::get_instance();
Merakcamacol\Blocks\PostsCarousel::get_instance();
Merakcamacol\Blocks\Services::get_instance();
Merakcamacol\Blocks\SocialNetworks::get_instance();
Merakcamacol\Blocks\SupplierData::get_instance();
Merakcamacol\Blocks\SupplierRelatedNews::get_instance();
Merakcamacol\Blocks\TwigBlock::get_instance();
Merakcamacol\Importers\Funders::get_instance();
Merakcamacol\Importers\Suppliers::get_instance();
Merakcamacol\Settings\Site::get_instance();
Merakcamacol\Settings\SocialNetworks::get_instance();
Merakcamacol\Structures\Funder::get_instance();
Merakcamacol\Structures\Supplier::get_instance();
Merakcamacol\Structures\Fields\Cabecera::get_instance();
Merakcamacol\Widgets\SocialNetworks::get_instance();
Merakcamacol\WpJson\Sugerencias::get_instance();
